services:
  - type: web
    name: elevenlabs-backend
    env: python
    buildCommand: |
      chmod +x setup.sh
      ./setup.sh
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.8
      - key: PYTHONUNBUFFERED
        value: true
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: /opt/render/project/src
